<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Consulta_Vehiculos.Presentación</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Consulta Vehiculos.Negocios\Consulta Vehiculos.Negocios.csproj" />
  </ItemGroup>

</Project>
